### PR TITLE
Introduce the concept of Citizens

### PR DESCRIPTION
**Pull request by errrrk**
anonymous users are a vague concept, we should use something more descriptive for our domain. I think Citizen could be a good word to describe our anonymous users.

### CODE REVIEW

**Comment by dimitriirtimid** [comment]
I think this missing the point a bit. You propose to define citizens as 'Citizens are potential volunteers that have not signed up to participate in making a playground smokefree.' But that is not the same as anonymous users. The anonymous user is just someone (or something) who is not logged in. We don't know if it is a 'citizen', volunteer, administrator, ... 
We could also call it an unidentified or unauthenticated user... but I still think something along those lines.

**Comment by dimitriirtimid** [comment]
@errrrk could you check my response. Do you having another suggestion or shall we close this pr?

**Comment by KarianneHol** [comment]
I will ask Yvette.

**Comment by errrrk** [comment]
The reason for suggesting 'citizen' is that it's a word that was used during our talks at Longfonds. They mentioned 'burgers' signed a petition, and 'burgers' doing stuff. "Unauthenticated user" is typically technical jargon and not part of a customer's domain language.

**Pull request merged**
